### ISSUE TITLE
Silence mode

### ISSUE THREAD

**Issue by Bleuzen** [lsp-plugins/lsp-plugins-gate#2]
Hi, the current minimum reduction (-72 dB) is not enough. I try to make my mic signal silent when not speaking (so that compressed audio codecs could benefit from it and use less data for that regions). Currently this doesn't work. -72 dB still produces a signal that is picked up (especially with effects afterwards which amplify again), that doesn't help much with data compression.

Would be nice if you can add lower levels of reduction and a full mute as minimum value if possible.

**Comment by sadko4u** [comment]
Hello. For 'Silence mode' you can use Expander in downward mode.
